version: 2

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: vase-{{ checksum "project.clj" }}
      - run: lein install
      - save_cache:
          paths:
            - ~/.m2
          key: vase-{{ checksum "project.clj" }}
      - run: cd template && lein test
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/vase.jar
          destination: uberjar
